network:
  version: 2
  renderer: networkd
  ethernets:
    eno2:                       # arbitrary ID
      match:
        macaddress: 7c:c2:55:ad:41:81   # replace with your NIC MAC
      set-name: eno2          # optional: force interface name
      dhcp4: false
      dhcp6: false
  vlans:
    vlan.2106:
      id: 2106
      link: eno2
      addresses: [10.9.0.11/24]
